'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=1.1.4322.573.
'

'<remarks/>
<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="DeadOrAliveSoap", [Namespace]:="http://www.abundanttech.com/webservices/deadoralive")>  _
Public Class DeadOrAlive
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    '<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://www.abundanttech.com/WebServices/DeadOrAlive/DeadOrAlive.asmx"
    End Sub
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.abundanttech.com/webservices/deadoralive/getTodaysBirthdays", RequestNamespace:="http://www.abundanttech.com/webservices/deadoralive", ResponseNamespace:="http://www.abundanttech.com/webservices/deadoralive", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function getTodaysBirthdays() As System.Data.DataSet
        Dim results() As Object = Me.Invoke("getTodaysBirthdays", New Object(-1) {})
        Return CType(results(0),System.Data.DataSet)
    End Function
    
    '<remarks/>
    Public Function BegingetTodaysBirthdays(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getTodaysBirthdays", New Object(-1) {}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndgetTodaysBirthdays(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),System.Data.DataSet)
    End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.abundanttech.com/webservices/deadoralive/getDeadOrAlive", RequestNamespace:="http://www.abundanttech.com/webservices/deadoralive", ResponseNamespace:="http://www.abundanttech.com/webservices/deadoralive", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function getDeadOrAlive(ByVal sFullName As String) As System.Data.DataSet
        Dim results() As Object = Me.Invoke("getDeadOrAlive", New Object() {sFullName})
        Return CType(results(0),System.Data.DataSet)
    End Function
    
    '<remarks/>
    Public Function BegingetDeadOrAlive(ByVal sFullName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getDeadOrAlive", New Object() {sFullName}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndgetDeadOrAlive(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),System.Data.DataSet)
    End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.abundanttech.com/webservices/deadoralive/getBornOn", RequestNamespace:="http://www.abundanttech.com/webservices/deadoralive", ResponseNamespace:="http://www.abundanttech.com/webservices/deadoralive", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function getBornOn(ByVal sDate As String) As System.Data.DataSet
        Dim results() As Object = Me.Invoke("getBornOn", New Object() {sDate})
        Return CType(results(0),System.Data.DataSet)
    End Function
    
    '<remarks/>
    Public Function BegingetBornOn(ByVal sDate As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getBornOn", New Object() {sDate}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndgetBornOn(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),System.Data.DataSet)
    End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.abundanttech.com/webservices/deadoralive/getDiedOn", RequestNamespace:="http://www.abundanttech.com/webservices/deadoralive", ResponseNamespace:="http://www.abundanttech.com/webservices/deadoralive", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function getDiedOn(ByVal sDate As String) As System.Data.DataSet
        Dim results() As Object = Me.Invoke("getDiedOn", New Object() {sDate})
        Return CType(results(0),System.Data.DataSet)
    End Function
    
    '<remarks/>
    Public Function BegingetDiedOn(ByVal sDate As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getDiedOn", New Object() {sDate}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndgetDiedOn(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),System.Data.DataSet)
    End Function
End Class
